// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NeighborApplyConfiguration represents a declarative configuration of the Neighbor type for use
// with apply.
//
// Neighbor represents a connected neighbor device.
type NeighborApplyConfiguration struct {
	// MacAddress is the MAC address of the neighbor device.
	MacAddress *string `json:"macAddress,omitempty"`
	// SystemName is the name of the neighbor device.
	SystemName *string `json:"systemName,omitempty"`
	// InterfaceHandle is the name of the remote switch interface.
	InterfaceHandle *string `json:"interfaceHandle,omitempty"`
}

// NeighborApplyConfiguration constructs a declarative configuration of the Neighbor type for use with
// apply.
func Neighbor() *NeighborApplyConfiguration {
	return &NeighborApplyConfiguration{}
}

// WithMacAddress sets the MacAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MacAddress field is set to the value of the last call.
func (b *NeighborApplyConfiguration) WithMacAddress(value string) *NeighborApplyConfiguration {
	b.MacAddress = &value
	return b
}

// WithSystemName sets the SystemName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemName field is set to the value of the last call.
func (b *NeighborApplyConfiguration) WithSystemName(value string) *NeighborApplyConfiguration {
	b.SystemName = &value
	return b
}

// WithInterfaceHandle sets the InterfaceHandle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InterfaceHandle field is set to the value of the last call.
func (b *NeighborApplyConfiguration) WithInterfaceHandle(value string) *NeighborApplyConfiguration {
	b.InterfaceHandle = &value
	return b
}
