// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SwitchInterfaceStatusApplyConfiguration represents a declarative configuration of the SwitchInterfaceStatus type for use
// with apply.
//
// SwitchInterfaceStatus defines the observed state of SwitchInterface.
type SwitchInterfaceStatusApplyConfiguration struct {
	// AdminState represents the desired administrative state of the interface.
	AdminState *apiv1alpha1.AdminState `json:"adminState,omitempty"`
	// OperationalState represents the actual operational state of the interface.
	OperationalState *apiv1alpha1.OperationState `json:"operationalState,omitempty"`
	// State represents the high-level state of the SwitchInterface.
	State *apiv1alpha1.SwitchInterfaceState `json:"state,omitempty"`
	// Neighbor is a reference to the connected neighbor device, if any.
	Neighbor *NeighborApplyConfiguration `json:"neighbor,omitempty"`
	// MacAddress is the MAC address assigned to this interface.
	MacAddress *string `json:"macAddress,omitempty"`
	// AliasName is the alias name of the interface.
	AliasName *string `json:"aliasName,omitempty"`
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SwitchInterfaceStatusApplyConfiguration constructs a declarative configuration of the SwitchInterfaceStatus type for use with
// apply.
func SwitchInterfaceStatus() *SwitchInterfaceStatusApplyConfiguration {
	return &SwitchInterfaceStatusApplyConfiguration{}
}

// WithAdminState sets the AdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminState field is set to the value of the last call.
func (b *SwitchInterfaceStatusApplyConfiguration) WithAdminState(value apiv1alpha1.AdminState) *SwitchInterfaceStatusApplyConfiguration {
	b.AdminState = &value
	return b
}

// WithOperationalState sets the OperationalState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperationalState field is set to the value of the last call.
func (b *SwitchInterfaceStatusApplyConfiguration) WithOperationalState(value apiv1alpha1.OperationState) *SwitchInterfaceStatusApplyConfiguration {
	b.OperationalState = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *SwitchInterfaceStatusApplyConfiguration) WithState(value apiv1alpha1.SwitchInterfaceState) *SwitchInterfaceStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithNeighbor sets the Neighbor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Neighbor field is set to the value of the last call.
func (b *SwitchInterfaceStatusApplyConfiguration) WithNeighbor(value *NeighborApplyConfiguration) *SwitchInterfaceStatusApplyConfiguration {
	b.Neighbor = value
	return b
}

// WithMacAddress sets the MacAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MacAddress field is set to the value of the last call.
func (b *SwitchInterfaceStatusApplyConfiguration) WithMacAddress(value string) *SwitchInterfaceStatusApplyConfiguration {
	b.MacAddress = &value
	return b
}

// WithAliasName sets the AliasName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AliasName field is set to the value of the last call.
func (b *SwitchInterfaceStatusApplyConfiguration) WithAliasName(value string) *SwitchInterfaceStatusApplyConfiguration {
	b.AliasName = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SwitchInterfaceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SwitchInterfaceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
