// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/ironcore-dev/sonic-operator/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=sonic.networking.metal.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Neighbor"):
		return &apiv1alpha1.NeighborApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchCredentials"):
		return &apiv1alpha1.SwitchCredentialsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchInterface"):
		return &apiv1alpha1.SwitchInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchInterfaceSpec"):
		return &apiv1alpha1.SwitchInterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchInterfaceStatus"):
		return &apiv1alpha1.SwitchInterfaceStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
