// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/agent/proto/switch_agent.proto

package switchagentproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDeviceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceInfoRequest) Reset() {
	*x = GetDeviceInfoRequest{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoRequest) ProtoMessage() {}

func (x *GetDeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{1}
}

type GetDeviceInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Hwsku           string                 `protobuf:"bytes,2,opt,name=hwsku,proto3" json:"hwsku,omitempty"`
	LocalMacAddress string                 `protobuf:"bytes,3,opt,name=local_mac_address,json=localMacAddress,proto3" json:"local_mac_address,omitempty"`
	SonicOsVersion  string                 `protobuf:"bytes,4,opt,name=sonic_os_version,json=sonicOsVersion,proto3" json:"sonic_os_version,omitempty"`
	AsicType        string                 `protobuf:"bytes,5,opt,name=asic_type,json=asicType,proto3" json:"asic_type,omitempty"`
	Readiness       uint32                 `protobuf:"varint,6,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDeviceInfoResponse) Reset() {
	*x = GetDeviceInfoResponse{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoResponse) ProtoMessage() {}

func (x *GetDeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeviceInfoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetDeviceInfoResponse) GetHwsku() string {
	if x != nil {
		return x.Hwsku
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetLocalMacAddress() string {
	if x != nil {
		return x.LocalMacAddress
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetSonicOsVersion() string {
	if x != nil {
		return x.SonicOsVersion
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetAsicType() string {
	if x != nil {
		return x.AsicType
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetReadiness() uint32 {
	if x != nil {
		return x.Readiness
	}
	return 0
}

// The interface message containing details about a single interface.
type Interface struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OperationalStatus uint32                 `protobuf:"varint,2,opt,name=operational_status,json=operationalStatus,proto3" json:"operational_status,omitempty"`
	AdminStatus       uint32                 `protobuf:"varint,3,opt,name=admin_status,json=adminStatus,proto3" json:"admin_status,omitempty"`
	MacAddress        string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetOperationalStatus() uint32 {
	if x != nil {
		return x.OperationalStatus
	}
	return 0
}

func (x *Interface) GetAdminStatus() uint32 {
	if x != nil {
		return x.AdminStatus
	}
	return 0
}

func (x *Interface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

// The request message containing the parameters for the request.
type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{4}
}

// The response message containing the list of interfaces.
type ListInterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Interfaces    []*Interface           `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesResponse) Reset() {
	*x = ListInterfacesResponse{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponse) ProtoMessage() {}

func (x *ListInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesResponse.ProtoReflect.Descriptor instead.
func (*ListInterfacesResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListInterfacesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListInterfacesResponse) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type SetInterfaceAdminStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	AdminStatus   uint32                 `protobuf:"varint,2,opt,name=admin_status,json=adminStatus,proto3" json:"admin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInterfaceAdminStatusRequest) Reset() {
	*x = SetInterfaceAdminStatusRequest{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInterfaceAdminStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceAdminStatusRequest) ProtoMessage() {}

func (x *SetInterfaceAdminStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceAdminStatusRequest.ProtoReflect.Descriptor instead.
func (*SetInterfaceAdminStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SetInterfaceAdminStatusRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetInterfaceAdminStatusRequest) GetAdminStatus() uint32 {
	if x != nil {
		return x.AdminStatus
	}
	return 0
}

type SetInterfaceAdminStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Interface     *Interface             `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInterfaceAdminStatusResponse) Reset() {
	*x = SetInterfaceAdminStatusResponse{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInterfaceAdminStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceAdminStatusResponse) ProtoMessage() {}

func (x *SetInterfaceAdminStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceAdminStatusResponse.ProtoReflect.Descriptor instead.
func (*SetInterfaceAdminStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SetInterfaceAdminStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SetInterfaceAdminStatusResponse) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

type ListPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortsRequest) Reset() {
	*x = ListPortsRequest{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortsRequest) ProtoMessage() {}

func (x *ListPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortsRequest.ProtoReflect.Descriptor instead.
func (*ListPortsRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{8}
}

type ListPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Ports         []*Port                `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortsResponse) Reset() {
	*x = ListPortsResponse{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortsResponse) ProtoMessage() {}

func (x *ListPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortsResponse.ProtoReflect.Descriptor instead.
func (*ListPortsResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ListPortsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListPortsResponse) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Port) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type GetInterfaceNeighborRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfaceNeighborRequest) Reset() {
	*x = GetInterfaceNeighborRequest{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceNeighborRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceNeighborRequest) ProtoMessage() {}

func (x *GetInterfaceNeighborRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceNeighborRequest.ProtoReflect.Descriptor instead.
func (*GetInterfaceNeighborRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{11}
}

func (x *GetInterfaceNeighborRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type InterfaceNeighbor struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NeighborInterfaceName string                 `protobuf:"bytes,1,opt,name=neighbor_interface_name,json=neighborInterfaceName,proto3" json:"neighbor_interface_name,omitempty"`
	MacAddress            string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	SystemName            string                 `protobuf:"bytes,3,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InterfaceNeighbor) Reset() {
	*x = InterfaceNeighbor{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceNeighbor) ProtoMessage() {}

func (x *InterfaceNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceNeighbor.ProtoReflect.Descriptor instead.
func (*InterfaceNeighbor) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{12}
}

func (x *InterfaceNeighbor) GetNeighborInterfaceName() string {
	if x != nil {
		return x.NeighborInterfaceName
	}
	return ""
}

func (x *InterfaceNeighbor) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *InterfaceNeighbor) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

type GetInterfaceNeighborResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Neighbor      *InterfaceNeighbor     `protobuf:"bytes,3,opt,name=neighbor,proto3" json:"neighbor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfaceNeighborResponse) Reset() {
	*x = GetInterfaceNeighborResponse{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceNeighborResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceNeighborResponse) ProtoMessage() {}

func (x *GetInterfaceNeighborResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceNeighborResponse.ProtoReflect.Descriptor instead.
func (*GetInterfaceNeighborResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetInterfaceNeighborResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetInterfaceNeighborResponse) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *GetInterfaceNeighborResponse) GetNeighbor() *InterfaceNeighbor {
	if x != nil {
		return x.Neighbor
	}
	return nil
}

type GetInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfaceRequest) Reset() {
	*x = GetInterfaceRequest{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceRequest) ProtoMessage() {}

func (x *GetInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceRequest.ProtoReflect.Descriptor instead.
func (*GetInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetInterfaceRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type GetInterfaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Interface     *Interface             `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfaceResponse) Reset() {
	*x = GetInterfaceResponse{}
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceResponse) ProtoMessage() {}

func (x *GetInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_switch_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceResponse.ProtoReflect.Descriptor instead.
func (*GetInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_switch_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetInterfaceResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetInterfaceResponse) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

var File_internal_agent_proto_switch_agent_proto protoreflect.FileDescriptor

const file_internal_agent_proto_switch_agent_proto_rawDesc = "" +
	"\n" +
	"'internal/agent/proto/switch_agent.proto\x12\x0eswitchagent.v1\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetDeviceInfoRequest\"\xee\x01\n" +
	"\x15GetDeviceInfoResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\x12\x14\n" +
	"\x05hwsku\x18\x02 \x01(\tR\x05hwsku\x12*\n" +
	"\x11local_mac_address\x18\x03 \x01(\tR\x0flocalMacAddress\x12(\n" +
	"\x10sonic_os_version\x18\x04 \x01(\tR\x0esonicOsVersion\x12\x1b\n" +
	"\tasic_type\x18\x05 \x01(\tR\basicType\x12\x1c\n" +
	"\treadiness\x18\x06 \x01(\rR\treadiness\"\x92\x01\n" +
	"\tInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x12operational_status\x18\x02 \x01(\rR\x11operationalStatus\x12!\n" +
	"\fadmin_status\x18\x03 \x01(\rR\vadminStatus\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\"\x17\n" +
	"\x15ListInterfacesRequest\"\x83\x01\n" +
	"\x16ListInterfacesResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\x129\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2\x19.switchagent.v1.InterfaceR\n" +
	"interfaces\"j\n" +
	"\x1eSetInterfaceAdminStatusRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12!\n" +
	"\fadmin_status\x18\x02 \x01(\rR\vadminStatus\"\x8a\x01\n" +
	"\x1fSetInterfaceAdminStatusResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\x127\n" +
	"\tinterface\x18\x02 \x01(\v2\x19.switchagent.v1.InterfaceR\tinterface\"\x12\n" +
	"\x10ListPortsRequest\"o\n" +
	"\x11ListPortsResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\x12*\n" +
	"\x05ports\x18\x02 \x03(\v2\x14.switchagent.v1.PortR\x05ports\"0\n" +
	"\x04Port\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"D\n" +
	"\x1bGetInterfaceNeighborRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"\x8d\x01\n" +
	"\x11InterfaceNeighbor\x126\n" +
	"\x17neighbor_interface_name\x18\x01 \x01(\tR\x15neighborInterfaceName\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vsystem_name\x18\x03 \x01(\tR\n" +
	"systemName\"\xab\x01\n" +
	"\x1cGetInterfaceNeighborResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12=\n" +
	"\bneighbor\x18\x03 \x01(\v2!.switchagent.v1.InterfaceNeighborR\bneighbor\"<\n" +
	"\x13GetInterfaceRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"\x7f\n" +
	"\x14GetInterfaceResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\x127\n" +
	"\tinterface\x18\x02 \x01(\v2\x19.switchagent.v1.InterfaceR\tinterface2\xef\x04\n" +
	"\x12SwitchAgentService\x12\\\n" +
	"\rGetDeviceInfo\x12$.switchagent.v1.GetDeviceInfoRequest\x1a%.switchagent.v1.GetDeviceInfoResponse\x12_\n" +
	"\x0eListInterfaces\x12%.switchagent.v1.ListInterfacesRequest\x1a&.switchagent.v1.ListInterfacesResponse\x12z\n" +
	"\x17SetInterfaceAdminStatus\x12..switchagent.v1.SetInterfaceAdminStatusRequest\x1a/.switchagent.v1.SetInterfaceAdminStatusResponse\x12Y\n" +
	"\fGetInterface\x12#.switchagent.v1.GetInterfaceRequest\x1a$.switchagent.v1.GetInterfaceResponse\x12q\n" +
	"\x14GetInterfaceNeighbor\x12+.switchagent.v1.GetInterfaceNeighborRequest\x1a,.switchagent.v1.GetInterfaceNeighborResponse\x12P\n" +
	"\tListPorts\x12 .switchagent.v1.ListPortsRequest\x1a!.switchagent.v1.ListPortsResponseB\x14Z\x12./switchagentprotob\x06proto3"

var (
	file_internal_agent_proto_switch_agent_proto_rawDescOnce sync.Once
	file_internal_agent_proto_switch_agent_proto_rawDescData []byte
)

func file_internal_agent_proto_switch_agent_proto_rawDescGZIP() []byte {
	file_internal_agent_proto_switch_agent_proto_rawDescOnce.Do(func() {
		file_internal_agent_proto_switch_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_proto_switch_agent_proto_rawDesc), len(file_internal_agent_proto_switch_agent_proto_rawDesc)))
	})
	return file_internal_agent_proto_switch_agent_proto_rawDescData
}

var file_internal_agent_proto_switch_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_agent_proto_switch_agent_proto_goTypes = []any{
	(*Status)(nil),                          // 0: switchagent.v1.Status
	(*GetDeviceInfoRequest)(nil),            // 1: switchagent.v1.GetDeviceInfoRequest
	(*GetDeviceInfoResponse)(nil),           // 2: switchagent.v1.GetDeviceInfoResponse
	(*Interface)(nil),                       // 3: switchagent.v1.Interface
	(*ListInterfacesRequest)(nil),           // 4: switchagent.v1.ListInterfacesRequest
	(*ListInterfacesResponse)(nil),          // 5: switchagent.v1.ListInterfacesResponse
	(*SetInterfaceAdminStatusRequest)(nil),  // 6: switchagent.v1.SetInterfaceAdminStatusRequest
	(*SetInterfaceAdminStatusResponse)(nil), // 7: switchagent.v1.SetInterfaceAdminStatusResponse
	(*ListPortsRequest)(nil),                // 8: switchagent.v1.ListPortsRequest
	(*ListPortsResponse)(nil),               // 9: switchagent.v1.ListPortsResponse
	(*Port)(nil),                            // 10: switchagent.v1.Port
	(*GetInterfaceNeighborRequest)(nil),     // 11: switchagent.v1.GetInterfaceNeighborRequest
	(*InterfaceNeighbor)(nil),               // 12: switchagent.v1.InterfaceNeighbor
	(*GetInterfaceNeighborResponse)(nil),    // 13: switchagent.v1.GetInterfaceNeighborResponse
	(*GetInterfaceRequest)(nil),             // 14: switchagent.v1.GetInterfaceRequest
	(*GetInterfaceResponse)(nil),            // 15: switchagent.v1.GetInterfaceResponse
}
var file_internal_agent_proto_switch_agent_proto_depIdxs = []int32{
	0,  // 0: switchagent.v1.GetDeviceInfoResponse.status:type_name -> switchagent.v1.Status
	0,  // 1: switchagent.v1.ListInterfacesResponse.status:type_name -> switchagent.v1.Status
	3,  // 2: switchagent.v1.ListInterfacesResponse.interfaces:type_name -> switchagent.v1.Interface
	0,  // 3: switchagent.v1.SetInterfaceAdminStatusResponse.status:type_name -> switchagent.v1.Status
	3,  // 4: switchagent.v1.SetInterfaceAdminStatusResponse.interface:type_name -> switchagent.v1.Interface
	0,  // 5: switchagent.v1.ListPortsResponse.status:type_name -> switchagent.v1.Status
	10, // 6: switchagent.v1.ListPortsResponse.ports:type_name -> switchagent.v1.Port
	0,  // 7: switchagent.v1.GetInterfaceNeighborResponse.status:type_name -> switchagent.v1.Status
	12, // 8: switchagent.v1.GetInterfaceNeighborResponse.neighbor:type_name -> switchagent.v1.InterfaceNeighbor
	0,  // 9: switchagent.v1.GetInterfaceResponse.status:type_name -> switchagent.v1.Status
	3,  // 10: switchagent.v1.GetInterfaceResponse.interface:type_name -> switchagent.v1.Interface
	1,  // 11: switchagent.v1.SwitchAgentService.GetDeviceInfo:input_type -> switchagent.v1.GetDeviceInfoRequest
	4,  // 12: switchagent.v1.SwitchAgentService.ListInterfaces:input_type -> switchagent.v1.ListInterfacesRequest
	6,  // 13: switchagent.v1.SwitchAgentService.SetInterfaceAdminStatus:input_type -> switchagent.v1.SetInterfaceAdminStatusRequest
	14, // 14: switchagent.v1.SwitchAgentService.GetInterface:input_type -> switchagent.v1.GetInterfaceRequest
	11, // 15: switchagent.v1.SwitchAgentService.GetInterfaceNeighbor:input_type -> switchagent.v1.GetInterfaceNeighborRequest
	8,  // 16: switchagent.v1.SwitchAgentService.ListPorts:input_type -> switchagent.v1.ListPortsRequest
	2,  // 17: switchagent.v1.SwitchAgentService.GetDeviceInfo:output_type -> switchagent.v1.GetDeviceInfoResponse
	5,  // 18: switchagent.v1.SwitchAgentService.ListInterfaces:output_type -> switchagent.v1.ListInterfacesResponse
	7,  // 19: switchagent.v1.SwitchAgentService.SetInterfaceAdminStatus:output_type -> switchagent.v1.SetInterfaceAdminStatusResponse
	15, // 20: switchagent.v1.SwitchAgentService.GetInterface:output_type -> switchagent.v1.GetInterfaceResponse
	13, // 21: switchagent.v1.SwitchAgentService.GetInterfaceNeighbor:output_type -> switchagent.v1.GetInterfaceNeighborResponse
	9,  // 22: switchagent.v1.SwitchAgentService.ListPorts:output_type -> switchagent.v1.ListPortsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_agent_proto_switch_agent_proto_init() }
func file_internal_agent_proto_switch_agent_proto_init() {
	if File_internal_agent_proto_switch_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_proto_switch_agent_proto_rawDesc), len(file_internal_agent_proto_switch_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agent_proto_switch_agent_proto_goTypes,
		DependencyIndexes: file_internal_agent_proto_switch_agent_proto_depIdxs,
		MessageInfos:      file_internal_agent_proto_switch_agent_proto_msgTypes,
	}.Build()
	File_internal_agent_proto_switch_agent_proto = out.File
	file_internal_agent_proto_switch_agent_proto_goTypes = nil
	file_internal_agent_proto_switch_agent_proto_depIdxs = nil
}
