// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/agent/proto/switch_agent.proto

package switchagentproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwitchAgentService_GetDeviceInfo_FullMethodName           = "/switchagent.v1.SwitchAgentService/GetDeviceInfo"
	SwitchAgentService_ListInterfaces_FullMethodName          = "/switchagent.v1.SwitchAgentService/ListInterfaces"
	SwitchAgentService_SetInterfaceAdminStatus_FullMethodName = "/switchagent.v1.SwitchAgentService/SetInterfaceAdminStatus"
	SwitchAgentService_GetInterface_FullMethodName            = "/switchagent.v1.SwitchAgentService/GetInterface"
	SwitchAgentService_GetInterfaceNeighbor_FullMethodName    = "/switchagent.v1.SwitchAgentService/GetInterfaceNeighbor"
	SwitchAgentService_ListPorts_FullMethodName               = "/switchagent.v1.SwitchAgentService/ListPorts"
)

// SwitchAgentServiceClient is the client API for SwitchAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The interface service definition.
type SwitchAgentServiceClient interface {
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	SetInterfaceAdminStatus(ctx context.Context, in *SetInterfaceAdminStatusRequest, opts ...grpc.CallOption) (*SetInterfaceAdminStatusResponse, error)
	GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceResponse, error)
	GetInterfaceNeighbor(ctx context.Context, in *GetInterfaceNeighborRequest, opts ...grpc.CallOption) (*GetInterfaceNeighborResponse, error)
	ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error)
}

type switchAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchAgentServiceClient(cc grpc.ClientConnInterface) SwitchAgentServiceClient {
	return &switchAgentServiceClient{cc}
}

func (c *switchAgentServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SetInterfaceAdminStatus(ctx context.Context, in *SetInterfaceAdminStatusRequest, opts ...grpc.CallOption) (*SetInterfaceAdminStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInterfaceAdminStatusResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SetInterfaceAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetInterfaceNeighbor(ctx context.Context, in *GetInterfaceNeighborRequest, opts ...grpc.CallOption) (*GetInterfaceNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceNeighborResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetInterfaceNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortsResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchAgentServiceServer is the server API for SwitchAgentService service.
// All implementations must embed UnimplementedSwitchAgentServiceServer
// for forward compatibility.
//
// The interface service definition.
type SwitchAgentServiceServer interface {
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error)
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	SetInterfaceAdminStatus(context.Context, *SetInterfaceAdminStatusRequest) (*SetInterfaceAdminStatusResponse, error)
	GetInterface(context.Context, *GetInterfaceRequest) (*GetInterfaceResponse, error)
	GetInterfaceNeighbor(context.Context, *GetInterfaceNeighborRequest) (*GetInterfaceNeighborResponse, error)
	ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error)
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

// UnimplementedSwitchAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwitchAgentServiceServer struct{}

func (UnimplementedSwitchAgentServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedSwitchAgentServiceServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SetInterfaceAdminStatus(context.Context, *SetInterfaceAdminStatusRequest) (*SetInterfaceAdminStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInterfaceAdminStatus not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetInterface(context.Context, *GetInterfaceRequest) (*GetInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetInterfaceNeighbor(context.Context, *GetInterfaceNeighborRequest) (*GetInterfaceNeighborResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterfaceNeighbor not implemented")
}
func (UnimplementedSwitchAgentServiceServer) ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedSwitchAgentServiceServer) mustEmbedUnimplementedSwitchAgentServiceServer() {}
func (UnimplementedSwitchAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeSwitchAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchAgentServiceServer will
// result in compilation errors.
type UnsafeSwitchAgentServiceServer interface {
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

func RegisterSwitchAgentServiceServer(s grpc.ServiceRegistrar, srv SwitchAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedSwitchAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwitchAgentService_ServiceDesc, srv)
}

func _SwitchAgentService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SetInterfaceAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInterfaceAdminStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SetInterfaceAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SetInterfaceAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SetInterfaceAdminStatus(ctx, req.(*SetInterfaceAdminStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetInterface(ctx, req.(*GetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetInterfaceNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetInterfaceNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetInterfaceNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetInterfaceNeighbor(ctx, req.(*GetInterfaceNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).ListPorts(ctx, req.(*ListPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwitchAgentService_ServiceDesc is the grpc.ServiceDesc for SwitchAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.SwitchAgentService",
	HandlerType: (*SwitchAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _SwitchAgentService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _SwitchAgentService_ListInterfaces_Handler,
		},
		{
			MethodName: "SetInterfaceAdminStatus",
			Handler:    _SwitchAgentService_SetInterfaceAdminStatus_Handler,
		},
		{
			MethodName: "GetInterface",
			Handler:    _SwitchAgentService_GetInterface_Handler,
		},
		{
			MethodName: "GetInterfaceNeighbor",
			Handler:    _SwitchAgentService_GetInterfaceNeighbor_Handler,
		},
		{
			MethodName: "ListPorts",
			Handler:    _SwitchAgentService_ListPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}
